import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
  candidates: [
    {
      registrationNo: 30,
      registrationDate: new Date("1970-01-01"),
      samajName: 'Sample       samajName',
      NRI: false,
      gender: 'M',
      name: 'Steve',
      middleName: 'Sample       middleName',
      lastName: 'Smith',
      currentAddress: 'Gandhinagar',
      permenantAddress: 'Sample       permenantAddress',
      parentsMobile: 30,
      email: 'Sample       email',
      native: 'Sample       native',
      birthDate: new Date("1995-06-15"),
      birthTime: new Date("1995-06-15"),
      birthPlace: 'Sample       birthPlace',
      subCaste: 'Sample       subCaste',
      mosal: 'Sample       mosal',
      height: '5-9',
      weight: 30,
      eyeSight: true,
      horoscopeBelief: true,
      saniMangal: true,
      complexion: 'Sample       complexion',
      disability: true,
      hobby: 'Sample       hobby',
      maritalStatus: 'Sample       maritalStatus',
      marriageDate: new Date("1970-01-01"),
      divorceDate: new Date("1970-01-01"),
      childResponsibility: true,
      education: 'B.E. Mechanical',
      occupation: 'Sample       occupation',
      title: 'Sample       title',
      workAddress: 'Sample       workAddress',
      otherQualities: 'Sample       otherQualities',
      monthlyIncome: 30,
      currency: 'Sample       currency',
      ownHouse: true,
      preference: 'Sample       preference',
      familyBackground: 'Sample       familyBackground',
      fatherName: 'Sample       fatherName',
      fatherEducation: 'Sample       fatherEducation',
      fatherOccupation: 'Sample       fatherOccupation',
      fatherMobile: 30,
      motherName: 30,
      motherEducation: 'Sample       motherEducation',
      motherOccupation: 'Sample       motherOccupation',
      motherMobile: 30,
      familyIncome: 30,
      grandfatherName: 'Sample       grandfatherName',
      brothers: 30,
      brothersMaritalStatus: 'Sample       brothersMaritalStatus',
      sisters: 30,
      sistersMaritalStatus: 'Sample       sistersMaritalStatus',
      whyMe: 'Sample       whyMe',
      reference: true,
      refName: 'Sample       refName',
      refVillage: 'Sample       refVillage',
      refMobile: 30,
      image: '/images/shirt3.jpg',
    },
    {
      registrationNo: 30,
      registrationDate: new Date("1970-01-01"),
      samajName: 'Sample       samajName',
      NRI: true,
      gender: 'M',
      name: 'John',
      middleName: 'Sample       middleName',
      lastName: 'Doe',
      currentAddress: 'Toronto',
      permenantAddress: 'Sample       permenantAddress',
      parentsMobile: 30,
      email: 'Sample       email',
      native: 'Sample       native',
      birthDate: new Date("1995-10-14"),
      birthTime: new Date("1970-01-01"),
      birthPlace: 'Sample       birthPlace',
      subCaste: 'Sample       subCaste',
      mosal: 'Sample       mosal',
      height: '5-8',
      weight: 30,
      eyeSight: true,
      horoscopeBelief: true,
      saniMangal: true,
      complexion: 'Sample       complexion',
      disability: true,
      hobby: 'Sample       hobby',
      maritalStatus: 'Sample       maritalStatus',
      marriageDate: new Date("1970-01-01"),
      divorceDate: new Date("1970-01-01"),
      childResponsibility: true,
      education: 'B.Sc. Physics',
      occupation: 'Sample       occupation',
      title: 'Sample       title',
      workAddress: 'Sample       workAddress',
      otherQualities: 'Sample       otherQualities',
      monthlyIncome: 30,
      currency: 'Sample       currency',
      ownHouse: true,
      preference: 'Sample       preference',
      familyBackground: 'Sample       familyBackground',
      fatherName: 'Sample       fatherName',
      fatherEducation: 'Sample       fatherEducation',
      fatherOccupation: 'Sample       fatherOccupation',
      fatherMobile: 30,
      motherName: 30,
      motherEducation: 'Sample       motherEducation',
      motherOccupation: 'Sample       motherOccupation',
      motherMobile: 30,
      familyIncome: 30,
      grandfatherName: 'Sample       grandfatherName',
      brothers: 30,
      brothersMaritalStatus: 'Sample       brothersMaritalStatus',
      sisters: 30,
      sistersMaritalStatus: 'Sample       sistersMaritalStatus',
      whyMe: 'Sample       whyMe',
      reference: true,
      refName: 'Sample       refName',
      refVillage: 'Sample       refVillage',
      refMobile: 30,
      image: '/images/shirt2.jpg',

    },
    {
      registrationNo: 30,
      registrationDate: new Date("1970-01-01"),
      samajName: 'Sample       samajName',
      NRI: true,
      gender: 'F',
      name: 'Sarah',
      middleName: 'Sample       middleName',
      lastName: 'Clinton',
      currentAddress: 'Chicago',
      permenantAddress: 'Sample       permenantAddress',
      parentsMobile: 30,
      email: 'Sample       email',
      native: 'Sample       native',
      birthDate: new Date("1997-04-25"),
      birthTime: new Date("1970-01-01"),
      birthPlace: 'Sample       birthPlace',
      subCaste: 'Sample       subCaste',
      mosal: 'Sample       mosal',
      height: '4-11',
      weight: 30,
      eyeSight: true,
      horoscopeBelief: true,
      saniMangal: true,
      complexion: 'Sample       complexion',
      disability: true,
      hobby: 'Sample       hobby',
      maritalStatus: 'Sample       maritalStatus',
      marriageDate: new Date("1970-01-01"),
      divorceDate: new Date("1970-01-01"),
      childResponsibility: true,
      education: 'M.D. Cardiologist',
      occupation: 'Sample       occupation',
      title: 'Sample       title',
      workAddress: 'Sample       workAddress',
      otherQualities: 'Sample       otherQualities',
      monthlyIncome: 30,
      currency: 'Sample       currency',
      ownHouse: true,
      preference: 'Sample       preference',
      familyBackground: 'Sample       familyBackground',
      fatherName: 'Sample       fatherName',
      fatherEducation: 'Sample       fatherEducation',
      fatherOccupation: 'Sample       fatherOccupation',
      fatherMobile: 30,
      motherName: 30,
      motherEducation: 'Sample       motherEducation',
      motherOccupation: 'Sample       motherOccupation',
      motherMobile: 30,
      familyIncome: 30,
      grandfatherName: 'Sample       grandfatherName',
      brothers: 30,
      brothersMaritalStatus: 'Sample       brothersMaritalStatus',
      sisters: 30,
      sistersMaritalStatus: 'Sample       sistersMaritalStatus',
      whyMe: 'Sample       whyMe',
      reference: true,
      refName: 'Sample       refName',
      refVillage: 'Sample       refVillage',
      refMobile: 30,
      image: '/images/Sarah.jpg',

    },
    {
      registrationNo: 30,
      registrationDate: new Date("1970-01-01"),
      samajName: 'Sample       samajName',
      NRI: true,
      gender: 'F',
      name: 'Karen',
      middleName: 'Sample       middleName',
      lastName: 'Murphy',
      currentAddress: 'Sydney',
      permenantAddress: 'Sample       permenantAddress',
      parentsMobile: 30,
      email: 'Sample       email',
      native: 'Sample       native',
      birthDate: new Date("1998-08-19"),
      birthTime: new Date("1970-01-01"),
      birthPlace: 'Sample       birthPlace',
      subCaste: 'Sample       subCaste',
      mosal: 'Sample       mosal',
      height: '5-1',
      weight: 30,
      eyeSight: true,
      horoscopeBelief: true,
      saniMangal: true,
      complexion: 'Sample       complexion',
      disability: true,
      hobby: 'Sample       hobby',
      maritalStatus: 'Sample       maritalStatus',
      marriageDate: new Date("1970-01-01"),
      divorceDate: new Date("1970-01-01"),
      childResponsibility: true,
      education: 'M.S. Computer Science',
      occupation: 'Sample       occupation',
      title: 'Sample       title',
      workAddress: 'Sample       workAddress',
      otherQualities: 'Sample       otherQualities',
      monthlyIncome: 30,
      currency: 'Sample       currency',
      ownHouse: true,
      preference: 'Sample       preference',
      familyBackground: 'Sample       familyBackground',
      fatherName: 'Sample       fatherName',
      fatherEducation: 'Sample       fatherEducation',
      fatherOccupation: 'Sample       fatherOccupation',
      fatherMobile: 30,
      motherName: 30,
      motherEducation: 'Sample       motherEducation',
      motherOccupation: 'Sample       motherOccupation',
      motherMobile: 30,
      familyIncome: 30,
      grandfatherName: 'Sample       grandfatherName',
      brothers: 30,
      brothersMaritalStatus: 'Sample       brothersMaritalStatus',
      sisters: 30,
      sistersMaritalStatus: 'Sample       sistersMaritalStatus',
      whyMe: 'Sample       whyMe',
      reference: true,
      refName: 'Sample       refName',
      refVillage: 'Sample       refVillage',
      refMobile: 30,
      image: '/images/Karen.jpg',

    },
  ],
  scrambleGame: [
    {
      gameNo: 1,
      gameDate: new Date("2022-03-14"),
      category: 'Science',
      clue: 'PIDAY',
      scrambledClue: 'DPYAI',
    },
    {
      gameNo: 2,
      gameDate: new Date("2022-03-15"),
      category: 'Geography',
      clue: 'EVEREST',
      scrambledClue: 'REEVETS',
    },
    {
      gameNo: 3,
      gameDate: new Date("2022-03-16"),
      category: 'MATH',
      clue: 'PARABOLA',
      scrambledClue: 'ALOBAPRA',
    },
    {
      gameNo: 4,
      gameDate: new Date("2022-03-17"),
      category: 'LEADER',
      clue: 'CHURCHILL',
      scrambledClue: 'CRULILHCH',
    },
  ],
};
export default data;
